DROP SCHEMA IF EXISTS ThirteenF;

CREATE SCHEMA IF NOT EXISTS ThirteenF;

USE ThirteenF;

DROP TABLE IF EXISTS SUBMISSION;
DROP TABLE IF EXISTS COVERPAGE;
DROP TABLE IF EXISTS INFOTABLE;

-- 5.1 SUBMISSION
CREATE TABLE SUBMISSION (
    ACCESSION_NUMBER VARCHAR(25) NOT NULL PRIMARY KEY,
    FILING_DATE DATE NOT NULL,
    SUBMISSIONTYPE VARCHAR(10) NOT NULL,
    CIK VARCHAR(10) NOT NULL,
    PERIODOFREPORT DATE NOT NULL
);

-- 5.2 COVERPAGE
CREATE TABLE COVERPAGE (
    ACCESSION_NUMBER VARCHAR(25) NOT NULL,
    REPORTCALENDARORQUARTER DATE NOT NULL,
    ISAMENDMENT CHAR(1),
    AMENDMENTNO INT,
    AMENDMENTTYPE VARCHAR(50),
    CONFDENIEDEXPIRED CHAR(1),
    DATEDENIEDEXPIRED DATE,
    DATEREPORTED DATE,
    REASONFORNONCONFIDENTIALITY VARCHAR(255),
    FILINGMANAGER_NAME VARCHAR(150) NOT NULL,
    PRIMARY KEY (ACCESSION_NUMBER)
);

-- 5.3 INFOTABLE
CREATE TABLE INFOTABLE (
    ACCESSION_NUMBER VARCHAR(25) NOT NULL,
    INFOTABLE_SK BIGINT NOT NULL,
    NAMEOFISSUER VARCHAR(200) NOT NULL,
    TITLEOFCLASS VARCHAR(150) NOT NULL,
    CUSIP CHAR(9) NOT NULL,
    FIGI VARCHAR(1),
    VALUE BIGINT NOT NULL,
    SSHPRNAMT BIGINT,
    SSHPRNAMTTYPE VARCHAR(10),
    PUTCALL VARCHAR(10),
    INVESTMENTDISCRETION VARCHAR(10),
    OTHERMANAGER VARCHAR(100),
    VOTING_AUTH_SOLE BIGINT ,
    VOTING_AUTH_SHARED BIGINT ,
    VOTING_AUTH_NONE BIGINT,
    PRIMARY KEY (ACCESSION_NUMBER, INFOTABLE_SK)
);

# Enable local infile loading if needed
SET GLOBAL local_infile=1;
