SELECT 
    it.NAMEOFISSUER,
    it.TITLEOFCLASS,
    it.CUSIP,
    it.VALUE,
    cp.REPORTCALENDARORQUARTER,
    cp.FILINGMANAGER_NAME,
    sub.CIK,
    sub.PERIODOFREPORT
FROM ThirteenF.INFOTABLE as it
INNER JOIN ThirteenF.COVERPAGE as cp on cp.ACCESSION_NUMBER = it.ACCESSION_NUMBER
INNER JOIN ThirteenF.SUBMISSION as sub on sub.ACCESSION_NUMBER = it.ACCESSION_NUMBER
WHERE sub.CIK = '0000007773' AND
(TITLEOFCLASS LIKE '%stock%' OR TITLEOFCLASS LIKE '%equity%');